server:
  port: 8081
  error:
    include-message: always

apiBaseUrl:
  https://api.kinopoisk.dev

apiKey:
  7TTMP2W-5T8MW0G-QW83Z94-9R5G3YG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviemate
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
